# Generated by Django 4.2 on 2025-01-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="introduce",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
